
[build]
target = "index.html"
release = true
dist = "dist"
public_url = "/"

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = ["./stylesheet", "./asset", "index.html"]
# Paths to ignore.
# ignore = []

[serve]
# The address to serve on.
addr = "127.0.0.1"
# The port to serve on.
port = 3000
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = false

[clean]
# The output dir for all final assets.
dist = "dist"
# Optionally perform a cargo clean.
cargo = false

[tools]
# Default wasm-opt version to download.
wasm_opt = "version_101"